POST localhost:5001/api/auth/authenticate
Content-Type: application/json

{
    "Email":"someE@gmail.com",
    "Password":"123123"
}
###
GET https://localhost:5001/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIkFkbWluIiwiTW9kZXJhdG9yIiwiVXNlciJdLCJlbWFpbCI6InNvbWVFQGdtYWlsLmNvbSIsIm5iZiI6MTU5ODEwMTkwNywiZXhwIjoxNTk4MTAyMjA3LCJpYXQiOjE1OTgxMDE5MDd9.EtdVjbJwTlgF_XplWsJUUp9sKUShKn5z8mqdqkjHn9k
###
