GET https://localhost:5001/api/post
###
GET https://localhost:5001/api/post/getUserById/1
###
POST https://localhost:5001/api/post
Content-Type: application/json

{
    "Author_Id":1,
    "Post_Type_Id":3,
    "Title":"test post 4 with images",
    "Post_Content":"It will be fun !!!!????))))",
    "Date":"2020-08-13T11:30:00",
    "Post_Rate":1,
    "Post_Images":[
        {
            "Image_Id":2,
            "Post_Id":8
        },{
            "Image_Id":3,
            "Post_Id":8
        }
    ]
}
###

PUT https://localhost:5001/api/post
Content-Type: application/json

{
    "Id":8,
    "Author_Id":1,
    "Post_Type_Id":3,
    "Title":"test post 2 with images",
    "Post_Content":"It will be fun ))))",
    "Date":"2020-08-13T10:30:00",
    "Post_Rate":1,
    "Post_Images":[
        {
            "Image_Id":1,
            "Post_Id":8
        },{
            "Image_Id":2,
            "Post_Id":8
        },{
            "Image_Id":3,
            "Post_Id":8
        }
    ]
}
###
DELETE https://localhost:5001/api/post/9